#!/usr/bin/env python3
"""Phase 1 data migration — preserve the single-tenant beta history.

Reads the current data/positions/{open,closed}_positions.json and emits a
Supabase seed migration (supabase/migrations/0002_seed_official_beta.sql) that
inserts them as OFFICIAL BETA rows (user_id NULL, is_official_beta = true), so
the global beta dashboard keeps its track record after the move to Postgres.

This only GENERATES SQL (and verifies fidelity); applying it to a real Supabase
project is a manual `supabase db push` / SQL-editor step (no creds in this env).
Re-runnable and deterministic — the seed is idempotent-safe to review.

Usage:
    python scripts/migrate_positions_to_supabase.py          # generate + verify
    python scripts/migrate_positions_to_supabase.py --check   # verify only
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT        = Path(__file__).parent.parent
_OPEN_FILE   = _ROOT / "data" / "positions" / "open_positions.json"
_CLOSED_FILE = _ROOT / "data" / "positions" / "closed_positions.json"
_SEED_FILE   = _ROOT / "supabase" / "migrations" / "0002_seed_official_beta.sql"

# positions columns the seed writes, in order.
_COLS = ["user_id", "is_official_beta", "ticker", "entry_date", "entry_price",
         "signal_composite", "signal_drawdown", "status", "exit_date",
         "exit_price", "realized_return", "days_held", "reminder_sent"]


def _load(path: Path) -> list[dict]:
    if not path.exists():
        return []
    data = json.loads(path.read_text())
    return data if isinstance(data, list) else []


def _sql_lit(v) -> str:
    """Render a Python value as a Postgres literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    # text / date → single-quoted, escape embedded quotes
    return "'" + str(v).replace("'", "''") + "'"


def _row(p: dict, status: str) -> dict:
    """Map one JSON position record → a positions-table row (official beta)."""
    return {
        "user_id":          None,
        "is_official_beta": True,
        "ticker":           p["ticker"],
        "entry_date":       p["entry_date"],
        "entry_price":      p["entry_price"],
        "signal_composite": p.get("signal_composite"),
        "signal_drawdown":  p.get("signal_drawdown"),
        "status":           status,
        "exit_date":        p.get("exit_date"),
        "exit_price":       p.get("exit_price"),
        "realized_return":  p.get("realized_return"),
        "days_held":        p.get("days_held"),
        "reminder_sent":    bool(p.get("reminder_sent", False)),
    }


def build_rows() -> list[dict]:
    rows  = [_row(p, "open")   for p in _load(_OPEN_FILE)]
    rows += [_row(p, "closed") for p in _load(_CLOSED_FILE)]
    return rows


def render_sql(rows: list[dict]) -> str:
    head = [
        "-- Phase 1 seed — OFFICIAL BETA history migrated from data/positions/*.json.",
        "-- Generated by scripts/migrate_positions_to_supabase.py (do not hand-edit).",
        "-- Official-beta rows: user_id IS NULL + is_official_beta = true. Served by",
        "-- the global beta dashboard (never by per-user RLS).",
        "",
    ]
    if not rows:
        head.append("-- (No positions on file — nothing to migrate.)")
        return "\n".join(head) + "\n"
    head.append("insert into public.positions")
    head.append("  (" + ", ".join(_COLS) + ")")
    head.append("values")
    values = []
    for r in rows:
        values.append("  (" + ", ".join(_sql_lit(r[c]) for c in _COLS) + ")")
    return "\n".join(head) + "\n" + ",\n".join(values) + ";\n"


def verify(rows: list[dict]) -> None:
    """Confirm the seed rows faithfully reflect the JSON (count + key fields)."""
    n_open   = len(_load(_OPEN_FILE))
    n_closed = len(_load(_CLOSED_FILE))
    assert len(rows) == n_open + n_closed, "row count mismatch vs JSON"
    assert all(r["is_official_beta"] and r["user_id"] is None for r in rows), \
        "every migrated row must be official-beta with NULL user_id"
    # Every closed JSON record must appear with its exact realized_return + dates.
    for src in _load(_CLOSED_FILE):
        match = next((r for r in rows if r["ticker"] == src["ticker"]
                      and r["status"] == "closed"
                      and r["entry_date"] == src["entry_date"]
                      and r["exit_date"] == src.get("exit_date")
                      and r["realized_return"] == src.get("realized_return")), None)
        assert match is not None, f"closed position not faithfully migrated: {src}"
    print(f"  fidelity OK — {n_open} open + {n_closed} closed = {len(rows)} official-beta rows")


def main() -> int:
    rows = build_rows()
    verify(rows)
    if "--check" not in sys.argv:
        _SEED_FILE.parent.mkdir(parents=True, exist_ok=True)
        _SEED_FILE.write_text(render_sql(rows))
        print(f"  wrote {_SEED_FILE.relative_to(_ROOT)}")
    print("  migrated official-beta records:")
    for r in rows:
        extra = (f" exit={r['exit_date']} ret={r['realized_return']}"
                 if r["status"] == "closed" else "")
        print(f"    - {r['ticker']:<6} {r['status']:<6} entry={r['entry_date']} @ {r['entry_price']}{extra}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
