-- Phase 1 seed — OFFICIAL BETA history migrated from data/positions/*.json.
-- Generated by scripts/migrate_positions_to_supabase.py (do not hand-edit).
-- Official-beta rows: user_id IS NULL + is_official_beta = true. Served by
-- the global beta dashboard (never by per-user RLS).

insert into public.positions
  (user_id, is_official_beta, ticker, entry_date, entry_price, signal_composite, signal_drawdown, status, exit_date, exit_price, realized_return, days_held, reminder_sent)
values
  (null, true, 'ORCL', '2026-06-12', 184.1, null, null, 'closed', '2026-06-12', 184.10000610351562, 3.31532625796882e-08, 0, false);
