-- Phase 1 seed — OFFICIAL BETA history migrated from data/positions/*.json.
-- Generated by scripts/migrate_positions_to_supabase.py (do not hand-edit).
-- Official-beta rows: user_id IS NULL + is_official_beta = true. Served by
-- the global beta dashboard (never by per-user RLS).

-- (No positions on file — nothing to migrate.)
